apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    environment: production
spec:
  replicas: 4
  template:
    metadata:
      labels:
        environment: production
