apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
  labels:
    environment: production
    db-schema: v1.8
spec:
  replicas: 3
  template:
    metadata:
      labels:
        environment: production
