apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-demo
spec:
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 2
        - setWeight: 40
        - pause:
            duration: 2
        - setWeight: 60
        - pause:
            duration: 10
        - setWeight: 80
        - pause:
            duration: 2
